/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TabelaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TabelaModel;

/**
 *
 * @author jvalv
 */
public class JogosView extends javax.swing.JInternalFrame {

    private static int id = 1;
    public JogosView() {
        
        initComponents();
        edicaoComponentes();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlCodigo = new javax.swing.JLabel();
        jtxCodigo = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jlPlacar = new javax.swing.JLabel();
        jtxPlacar = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlCodigo.setText("Código: ");

        jtxCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxCodigo.setForeground(new java.awt.Color(0, 0, 255));

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlPlacar.setText("Placar");

        jtxPlacar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxPlacar.setForeground(new java.awt.Color(0, 0, 255));
        jtxPlacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxPlacarActionPerformed(evt);
            }
        });
        jtxPlacar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxPlacarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxPlacarKeyReleased(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Jogo", "Placar", "Minimo da temporada", "Máximo da temporada", "Quebra recorde min.", "Quebra recorde máx."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setHeaderValue("Jogo");
            tabela.getColumnModel().getColumn(1).setHeaderValue("Placar");
            tabela.getColumnModel().getColumn(2).setHeaderValue("Minimo da temporada");
            tabela.getColumnModel().getColumn(3).setHeaderValue("Máximo da temporada");
            tabela.getColumnModel().getColumn(4).setHeaderValue("Quebra recorde min.");
            tabela.getColumnModel().getColumn(5).setHeaderValue("Quebra recorde máx.");
        }

        jbSair.setText("SAIR");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbSair, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlPlacar)
                                .addComponent(jlCodigo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(jtxPlacar))
                            .addGap(18, 18, 18)
                            .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbSair)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPlacar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPlacar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        TabelaModel jogo = new TabelaModel();
        jogo.setIdJogo(Integer.parseInt(jtxCodigo.getText()));
        TabelaController controle = new TabelaController();
        jogo = controle.selecionarJogo(jogo);
        if(jogo !=null){
            jtxCodigo.setText((String.valueOf(jogo.getIdJogo())));
            jtxPlacar.setText((String.valueOf(jogo.getPlacar())));

            jtxCodigo.setEditable(false);
            jtxPlacar.setEditable(true);
            jbPesquisar.setEnabled(false);
            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "Jogo não encontrado!",
                "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtxPlacarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxPlacarKeyPressed


    }//GEN-LAST:event_jtxPlacarKeyPressed

    private void jtxPlacarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxPlacarKeyReleased

    }//GEN-LAST:event_jtxPlacarKeyReleased

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        TabelaController controle = new TabelaController();
        id = controle.ultimoIdJogos() + 1;
        limparCampos();
        jtxCodigo.setText(String.valueOf(id));
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbPesquisar.setEnabled(false);
        jtxCodigo.setEditable(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if(!jtxPlacar.getText().trim().equals("")){
            TabelaModel jogo = new TabelaModel();
            jogo.setIdJogo(Integer.parseInt(jtxCodigo.getText()));
            jogo.setPlacar(Integer.parseInt(jtxPlacar.getText()));
            
            TabelaController controle = new TabelaController();
            if(controle.InserirJogos(jogo)){
                JOptionPane.showMessageDialog(this, "Jogo Inserido com sucesso!");
                edicaoComponentes();
                limparCampos();
                atualizarTabela();
                jbNovo.setEnabled(true);
                jbPesquisar.setEnabled(true);
                jtxCodigo.setEditable(true);
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao Inserir jogo!",
                    "Retorno", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        TabelaModel jogo = new TabelaModel();
        jogo.setIdJogo(Integer.parseInt(jtxCodigo.getText()));
        TabelaController controle = new TabelaController();
        if(controle.editarJogos(jogo)){
            JOptionPane.showMessageDialog(this, "Jogo Editado com sucesso!");
            limparCampos();
            edicaoComponentes();
            atualizarTabela();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Editar jogo!",
                "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        TabelaModel jogo = new TabelaModel();
        TabelaController controle = new TabelaController();
        jtxCodigo.setText(String.valueOf(controle.ultimoIdJogos()));
        jogo.setIdJogo(Integer.parseInt(jtxCodigo.getText()));
        
        if(controle.excluirJogo(jogo)){
            JOptionPane.showMessageDialog(this, "Jogo Excluido com sucesso!");
            limparCampos();
            edicaoComponentes();
            atualizarTabela();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Excluir jogo!",
                "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtxPlacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxPlacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxPlacarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogosView().setVisible(true);
            }
        });
    }
    
    public void atualizarTabela(){
        TabelaController controle = new TabelaController();
        ArrayList<TabelaModel> lista = controle.selecionarTodosJogos();
        if(!lista.isEmpty()){
            DefaultTableModel modelo = (DefaultTableModel)tabela.getModel();
            modelo.setRowCount(0);
            for(TabelaModel j: lista){
                modelo.addRow(new String[]{
                    String.valueOf(j.getIdJogo()),
                    String.valueOf(j.getPlacar()),
                    String.valueOf(j.getMinTemp()),
                    String.valueOf(j.getMaxTemp()),
                    String.valueOf(j.getMinRecorde()),
                    String.valueOf(j.getMaxRecorde())
                });
            }
        }
    }
    private void edicaoComponentes(){
        jtxCodigo.setEditable(true);
        jtxPlacar.setEditable(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
    }
    public void limparCampos(){
       jtxCodigo.setText("");
       jtxPlacar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlPlacar;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxPlacar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
